blueprint:
  name: "Awtrix 3 Notification"
  description: "Send a notification to Awtrix 3 via MQTT."
  domain: automation
  author: "MrNick4B"
  homeassistant:
    min_version: "2024.6.0"
  source_url: "https://github.com/MrNick4B/HomeAssistant-Blueprints/blob/main/Awtrix/Notification/awtrix3-notification_nl.yaml"
  input:
    section_general:
      name: "General Settings"
      icon: mdi:cog
      description: "Configure the general settings."
      input:
        input_awtrix_device_topic:
          name: "MQTT Topic"
          description: "Select the Device Topic entity of the desired Awtrix device.\n(For example sensor.awtrix_xxxxxx_device_topic)"
          selector:
            entity:
              integration: mqtt
              domain: sensor
        input_duration:
          name: "Duration"
          description: "The duration for which the notification is displayed.\n0 = default duration of the device."
          default: 0
          selector:
            number:
              min: 0
              max: 60
              step: 1
              unit_of_measurement: "s"
        input_stack:
          name: "Stack Notification"
          description: "Wait to show a new notification until the current one is finished."
          default: true
          selector:
            boolean:
        input_app_update_trigger:
          name: "Trigger"
          description: "Trigger for displaying the notification."
          default: null
          selector:
            trigger:
        input_app_update_condition:
          name: "Condition"
          description: "Condition for displaying the notification."
          default: null
          selector:
            condition:
    section_text:
      name: "Text"
      icon: mdi:card-text
      description: "Configure the displayed text."
      input:
        input_text:
          name: "Text"
          description: "The text to be displayed. Also supports templates."
          default: null
          selector:
            template:
        input_text_entities:
          name: "Entities"
          description: "Select one or more entities whose status will be displayed."
          default: null
          selector:
            entity:
              multiple: true
        input_show_units:
          name: "Show Units"
          description: "Choose whether to display the units of the entities."
          default: true
          selector:
            boolean:
    section_icon:
      name: "Icon"
      icon: mdi:image
      description: "Customize the displayed icon."
      input:
        input_icon:
          name: "Icon"
          description: "Enter the ID or name of the icon."
          default: ""
          selector:
            text:
        input_icon_push:
          name: "Icon Movement"
          description: "Choose whether the icon moves with the text and how often this happens."
          default: "0"
          selector:
            select:
              options:
                - label: "Stays in place"
                  value: "0"
                - label: "Moves once with the text"
                  value: "1"
                - label: "Moves repeatedly with the text"
                  value: "2"
    section_textformatting:
      name: "Text Options"
      icon: mdi:format-text
      description: "Settings for text display."
      collapsed: true
      input:
        input_text_case:
          name: "Text Case"
          description: "Adjust the case of the text."
          default: "0"
          selector:
            select:
              options:
                - label: "Device default setting"
                  value: "0"
                - label: "Uppercase only"
                  value: "1"
                - label: "As entered"
                  value: "2"
        input_top_text:
          name: "Top Text"
          description: "Place the text on top of other content."
          default: false
          selector:
            boolean:
        input_blink_text:
          name: "Blinking Text"
          description: "Make the text blink. Does not work if the rainbow effect is enabled."
          default: 0
          selector:
            number:
              min: 0
              max: 5000
              step: 100
              unit_of_measurement: "ms"
        input_fade_text:
          name: "Fade Effect"
          description: "Make the text blink with a fade effect. Does not work if the rainbow effect is enabled."
          default: 0
          selector:
            number:
              min: 0
              max: 5000
              step: 100
              unit_of_measurement: "ms"
    section_colors:
      name: "Color Options"
      icon: mdi:palette
      description: "Customize the text and background colors."
      collapsed: true
      input:
        input_enable_text_color:
          name: "Enable Custom Text Color"
          description: "Does not work if the rainbow effect is enabled."
          default: "0"
          selector:
            select:
              options:
                - label: "No custom color"
                  value: "0"
                - label: "Single color"
                  value: "1"
                - label: "Gradient"
                  value: "2"
        input_text_color_1:
          name: "First Text Color"
          description: "For a gradient, the text starts with this color."
          default: [0, 128, 255]
          selector:
            color_rgb:
        input_text_color_2:
          name: "Second Text Color"
          description: "For a gradient, the text ends with this color."
          default: [255, 0, 128]
          selector:
            color_rgb:
        input_enable_background_color:
          name: "Enable Custom Background Color"
          description: "Enable the background color option."
          default: false
          selector:
            boolean:
        input_background_color:
          name: "Background Color"
          description: "Choose a custom background color."
          default: [255, 255, 255]
          selector:
            color_rgb:
        input_rainbow:
          name: "Rainbow Effect"
          description: "Give the text a rainbow effect. Overrides custom text color."
          default: false
          selector:
            boolean:
    section_effects:
      name: "Effects"
      icon: mdi:animation
      description: "Manage overlay and background effects."
      collapsed: true
      input:
        input_overlayeffect:
          name: "Overlay Effect"
          description: "Select an overlay effect."
          default: ""
          selector:
            select:
              options:
                - label: "No effect"
                  value: ""
                - label: "Clear"
                  value: "clear"
                - label: "Snow"
                  value: "snow"
                - label: "Rain"
                  value: "rain"
                - label: "Drizzle"
                  value: "drizzle"
                - label: "Storm"
                  value: "storm"
                - label: "Thunder"
                  value: "thunder"
                - label: "Frost"
                  value: "frost"
        input_backgroundeffect:
          name: "Background Effect"
          description: "Select a background effect."
          default: ""
          selector:
            select:
              options:
                - label: "No effect"
                  value: ""
                - label: "Fade"
                  value: "Fade"
                - label: "MovingLine"
                  value: "MovingLine"
                - label: "BrickBreaker"
                  value: "BrickBreaker"
                - label: "PingPong"
                  value: "PingPong"
                - label: "Radar"
                  value: "Radar"
                - label: "Checkerboard"
                  value: "Checkerboard"
                - label: "Fireworks"
                  value: "Fireworks"
                - label: "PlasmaCloud"
                  value: "PlasmaCloud"
                - label: "Ripple"
                  value: "Ripple"
                - label: "Snake"
                  value: "Snake"
                - label: "Pacifica"
                  value: "Pacifica"
                - label: "TheaterChase"
                  value: "TheaterChase"
                - label: "Plasma"
                  value: "Plasma"
                - label: "Matrix"
                  value: "Matrix"
                - label: "SwirlIn"
                  value: "SwirlIn"
                - label: "SwirlOut"
                  value: "SwirlOut"
                - label: "LookingEyes"
                  value: "LookingEyes"
                - label: "TwinklingStars"
                  value: "TwinklingStars"
                - label: "ColorWaves"
                  value: "ColorWaves"
    section_sounds:
      name: "Sounds"
      icon: mdi:music
      description: "Settings for sounds."
      collapsed: true
      input:
        input_rtttl:
          name: "RTTTL Sound"
          description: "RTTTL sound string to play when the notification is displayed."
          default: ""
          selector:
            text:
        input_loopSound:
          name: "Loop Sound"
          description: "Loop the sound as long as the notification is displayed."
          default: false
          selector:
            boolean:
    section_advanced:
      name: "Advanced Settings"
      icon: mdi:tune
      description: "Additional settings."
      collapsed: true
      input:
        input_wakeup:
          name: "Wake Up Screen"
          description: "Wake up the screen (matrix) if it is turned off. This does not work if the device is off."
          default: false
          selector:
            boolean:
mode: single

trigger:
  - triggers: !input input_app_update_trigger

condition:
  - and: !input input_app_update_condition

action:
  - variables:
      var_topic: !input input_awtrix_device_topic
      var_text: !input input_text
      var_text_entities: !input input_text_entities
      var_show_units: !input input_show_units
      var_stack: !input input_stack
      var_top_text: !input input_top_text
      var_text_case: !input input_text_case
      var_icon: !input input_icon
      var_icon_push: !input input_icon_push
      var_duration: !input input_duration
      var_rainbow: !input input_rainbow
      var_blink_text: !input input_blink_text
      var_fade_text: !input input_fade_text
      var_enable_text_color: !input input_enable_text_color
      var_text_color_1: !input input_text_color_1
      var_text_color_2: !input input_text_color_2
      var_enable_background_color: !input input_enable_background_color
      var_background_color: !input input_background_color
      var_overlayeffect: !input input_overlayeffect
      var_backgroundeffect: !input input_backgroundeffect
      var_rtttl: !input input_rtttl
      var_loopSound: !input input_loopSound
      wakeup: !input input_wakeup
      var_topicnotifyname: "{{ states(var_topic) }}/notify"
      blink: "{{ 0 if var_rainbow == 1 else var_blink_text }}"
      fade: "{{ 0 if var_rainbow == 1 else var_fade_text }}"
      var_combined_text: >
        {% set ns = namespace(result=[]) %}
        {% if var_text_entities %}
          {% for entity in var_text_entities %}
            {% set state = states(entity) %}
            {% set unit = state_attr(entity, "unit_of_measurement") %}
            {% if state not in ['unknown', 'unavailable', 'None'] %}
              {% if var_show_units and unit %}
                {% set ns.result = ns.result + [state ~ unit] %}
              {% else %}
                {% set ns.result = ns.result + [state] %}
              {% endif %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {% set entities_text = ns.result | join(' ') %}
        {% if var_text and entities_text %}
          {{ var_text }} {{ entities_text }}
        {% elif var_text %}
          {{ var_text }}
        {% elif entities_text %}
          {{ entities_text }}
        {% else %}
          ""
        {% endif %}
      payload_data: |
        {
          "stack": {{ var_stack | int }},
          "textCase": {{ var_text_case | int }},
          "topText": {{ var_top_text | int }},
          "rainbow": {{ var_rainbow | int }},
          "blinkText": {{ blink | int }},
          "fadeText": "{{ fade if fade != '0' else none }}",
          {% if var_enable_text_color == "1" %}
          "color": {{ var_text_color_1 }},
          {% endif %}
          {% if var_enable_text_color == "2" %}
          "gradient": [{{ var_text_color_1 }}, {{ var_text_color_2 }}],
          {% endif %}
          {% if var_enable_background_color %}
          "background": {{ var_background_color }},
          {% endif %}
          {% if var_icon %}
          "icon": "{{ var_icon }}",
          {% endif %}
          "pushIcon": "{{ var_icon_push | int }}",
          {% if (var_duration | int) > 0 %}
          "duration": {{ var_duration | int }},
          {% endif %}
          "overlay": "{{ var_overlayeffect }}",
          "effect": "{{ var_backgroundeffect }}",
          "wakeup": {{ wakeup | int }},
          {% if var_rtttl %}
          "rtttl": "{{ var_rtttl }}",
          {% endif %}
          "loopSound": {{ var_loopSound | int }},
          "text": "{{ var_combined_text }}"
        }
        
  - service: mqtt.publish
    data:
      topic: "{{ var_topicnotifyname }}"
      payload: "{{ payload_data }}"
